[*]

; GPU Performance
n-gpu-layers = all
n-gpu-layers-draft = all
flash-attn = on
fit = off
backend-sampling = on

; Overall Performance
prio = 3
prio-batch = 3

; Increased Batch Size
batch-size = 2048
ubatch-size = 1024

; Set budget message for max end performance
reasoning-budget-message = '\n\nI have enough to answer. Committing to my final answer now.\n'

[unsloth/gemma-4-26B-A4B-it-qat-GGUF:Q4_K_XL]

; Alias
alias = Gemma4

; Model Name
hf = unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL

; Chat Template (with system date injected)
chat-template-file = /config/templates/gemma4.jinja

; Spec Decoding
spec-type = draft-mtp
spec-draft-n-max = 4

; Tuning
temp = 1.0
top-p = 0.95
top-k = 64

; Image Tuning
image-min-tokens = 560
image-max-tokens = 1020

; Context Size
ctx-size = 108000
parallel = 6
cache-idle-slots = off
kvu = on
cache-ram = 4096

; Model Load Behavior
load-on-startup = true

[ggml-org/Qwen3-ASR-1.7B-GGUF:Q8_0]

; Alias
alias = Qwen3-ASR

; Model Name
hf = ggml-org/Qwen3-ASR-1.7B-GGUF:Q8_0

; Context Size
ctx-size = 896
parallel = 1
cache-ram = 0

; Model Load Behavior
load-on-startup = true
no-webui = true
