[*]

; Set Chat Template
jinja = true

; GPU Performance
n-gpu-layers = -1
flash-attn = on

; Overall Performance
prio = 3
prio-batch = 3

; Optimized Batch Size
batch-size = 2048
ubatch-size = 1024

[unsloth/gemma-4-26B-A4B-it-GGUF:Q4_K_XL]

; Alias
alias = Gemma4

; Model Name
hf = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL

; No Thinking by Default
reasoning = off

; Tuning
temp = 1.0
top-p = 0.95
top-k = 64

; Image Tuning
image-min-tokens = 280
image-max-tokens = 560

; Context Size
ctx-size = 204000
parallel = 6
slot-prompt-similarity = 0.4
cache-type-k = q8_0
cache-type-v = q8_0
cache-ram = 0

; Model Load Behavior
no-webui = false