[*]

; Set Chat Template
jinja = true

; GPU Performance
n-gpu-layers = -1
flash-attn = on

; Overall Performance
prio = 3
prio-batch = 3

; Increased Batch Size
batch-size = 2048
ubatch-size = 1024

; Set reasonable max thinking budgets
reasoning-budget = 3000
reasoning-budget-message = Taking too long, need to answer.

[unsloth/gemma-4-26B-A4B-GGUF:Q4_K_XL]

; Alias
alias = Gemma4

; Model Name
hf = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL

; Use Q8_0 mmproj from ggml-org for less VRAM
mmproj = /root/.cache/huggingface/hub/mmproj-gemma-4-26B-A4B-it-Q8_0.gguf

; Spec Decoding
spec-default = true

; No Thinking by Default
reasoning = off

; Tuning
temp = 1.0
top-p = 0.95
top-k = 64

; Image Tuning
image-min-tokens = 560
image-max-tokens = 1020

; Context Size
ctx-size = 120000
parallel = 3
slot-prompt-similarity = 0.4
cache-ram = 0

; Model Load Behavior
load-on-startup = true
no-webui = false
